import { useMemo, useState } from 'react'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { BellRing, ChevronLeft, ChevronRight, Flame, Gift } from 'lucide-react'
import clsx from 'clsx'
import { addDays, completionForInterval, dateKeyInTimeZone, formatDate, formatFullDate, isHabitDue } from '@/lib/date'
import { decideRedemption, toggleHabitCompletion } from '@/lib/points'
import { supabase } from '@/lib/supabase'
import type { AppSnapshot, Habit, Redemption } from '@/types'
import { AppIcon } from '@/components/AppIcon'
import { HabitCard } from '@/components/HabitCard'
import { Button, EmptyState, Notice } from '@/components/ui'

type PreviewComplete = (habitId: string) => { base_points_awarded: number; streak_bonus_awarded: number }
type PreviewUndo = (habitId: string) => void
type PreviewDecision = (redemptionId: string, decision: 'confirmed' | 'declined', reason?: string) => void

function RhythmStrip({ snapshot, userId, start, onPrevious, onNext }: { snapshot: AppSnapshot; userId: string; start: string; onPrevious: () => void; onNext: () => void }) {
  const dates = Array.from({ length: 7 }, (_, index) => addDays(start, index))
  return <section className="rounded-[26px] bg-white p-4 shadow-soft"><div className="mb-3 flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-wider text-ink/40">Your rhythm</p><h2 className="mt-0.5 font-black">This week</h2></div><div className="flex gap-1"><Button variant="ghost" size="icon" aria-label="Previous week" onClick={onPrevious}><ChevronLeft size={18} /></Button><Button variant="ghost" size="icon" aria-label="Next week" onClick={onNext}><ChevronRight size={18} /></Button></div></div><div className="grid grid-cols-7 gap-1.5">{dates.map((date) => { const due = snapshot.habits.filter((habit) => isHabitDue(habit, date, userId, snapshot.schedules)); const complete = due.filter((habit) => completionForInterval(habit.id, userId, date, snapshot.schedules, snapshot.completions)).length; return <div key={date} className="min-w-0 rounded-xl bg-app-bg px-1 py-2 text-center"><p className="text-[10px] font-black text-ink/45">{formatDate(date, { weekday: 'narrow' })}</p><p className="mt-1 text-sm font-black">{formatDate(date, { day: 'numeric' })}</p><div className={clsx('mx-auto mt-1 h-1.5 w-7 rounded-full', due.length && complete === due.length ? 'bg-emerald-500' : complete ? 'bg-accent' : due.length ? 'bg-surface' : 'bg-ink/10')} /><p className="mt-1 text-[9px] font-bold text-ink/40">{due.length ? `${complete}/${due.length}` : '—'}</p></div> })}</div><div className="mt-3 flex items-center gap-2 text-xs font-bold text-ink/50"><Flame size={15} className="text-accent" fill="currentColor" /> {snapshot.streaks.filter((item) => item.user_id === userId && item.current_streak > 0).length} habits currently in rhythm</div></section>
}

function ApprovalAlert({ redemption, snapshot, userId, onPreviewDecision }: { redemption: Redemption; snapshot: AppSnapshot; userId: string; onPreviewDecision?: PreviewDecision }) {
  const queryClient = useQueryClient(); const [error, setError] = useState('')
  const mutation = useMutation({ mutationFn: (decision: 'confirmed' | 'declined') => onPreviewDecision ? Promise.resolve(onPreviewDecision(redemption.id, decision)).then(() => redemption) : decideRedemption(supabase, redemption.id, decision), onSuccess: async () => queryClient.invalidateQueries({ queryKey: ['snapshot', userId] }), onError: (value) => setError((value as Error).message) })
  const requester = snapshot.profiles.find((profile) => profile.id === redemption.redeemed_by)?.display_name ?? 'Your partner'
  return <div className="rounded-2xl bg-surface/50 p-3"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-accent text-white"><Gift size={17} /></span><p className="min-w-0 flex-1 text-sm font-black"><span className="text-action">{requester}</span> wants {redemption.reward_name_snapshot}</p><Button size="sm" onClick={() => mutation.mutate('confirmed')} disabled={mutation.isPending}>Confirm</Button></div>{error && <div className="mt-2"><Notice>{error}</Notice></div>}</div>
}

export function DashboardPage({ snapshot, userId, onPreviewComplete, onPreviewDecision }: { snapshot: AppSnapshot; userId: string; onPreviewComplete?: PreviewComplete; onPreviewUndo?: PreviewUndo; onPreviewDecision?: PreviewDecision }) {
  const queryClient = useQueryClient(); const today = dateKeyInTimeZone(snapshot.settings.timezone)
  const [categoryId, setCategoryId] = useState('all'); const [weekStart, setWeekStart] = useState(today); const [completeError, setCompleteError] = useState('')
  const complete = useMutation({ mutationFn: (habitId: string) => onPreviewComplete ? Promise.resolve(onPreviewComplete(habitId)).then(() => undefined) : toggleHabitCompletion(supabase, habitId, today), onSuccess: async () => queryClient.invalidateQueries({ queryKey: ['snapshot', userId] }), onError: (error) => setCompleteError((error as Error).message) })
  const undo = complete
  const dueHabits = useMemo(() => snapshot.habits.filter((habit) => isHabitDue(habit, today, userId, snapshot.schedules) && (categoryId === 'all' || habit.category_id === categoryId)), [categoryId, snapshot.habits, snapshot.schedules, today, userId])
  const pendingIncoming = snapshot.redemptions.filter((item) => item.status === 'pending_confirmation' && item.redeemed_by !== userId)
  const remaining = dueHabits.filter((habit) => !completionForInterval(habit.id, userId, today, snapshot.schedules, snapshot.completions)).length
  return <div className="space-y-5"><div><p className="text-sm font-extrabold text-action">{formatFullDate(today)}</p><h1 className="mt-1 text-3xl font-black tracking-[-0.045em] sm:text-4xl">Today</h1><p className="mt-1 text-sm text-ink/55">{remaining ? `${remaining} small step${remaining === 1 ? '' : 's'} left.` : 'Everything is complete. Lovely work.'}</p></div>{completeError && <Notice>{completeError}</Notice>}<section className="min-h-[18rem]"><div className="mb-3 flex gap-2 overflow-x-auto pb-1"><button onClick={() => setCategoryId('all')} className={clsx('shrink-0 rounded-xl px-3 py-2 text-xs font-black', categoryId === 'all' ? 'bg-action text-white shadow-action' : 'bg-white text-ink/50')}>All</button>{snapshot.categories.map((category) => <button key={category.id} onClick={() => setCategoryId(category.id)} className={clsx('flex shrink-0 items-center gap-1.5 rounded-xl px-3 py-2 text-xs font-black', categoryId === category.id ? 'text-white shadow-action' : 'bg-white text-ink/50')} style={categoryId === category.id ? { backgroundColor: category.color } : undefined}><AppIcon name={category.icon} size={14} />{category.name}</button>)}</div>{dueHabits.length ? <div className="space-y-2">{dueHabits.map((habit: Habit) => { const completed = Boolean(completionForInterval(habit.id, userId, today, snapshot.schedules, snapshot.completions)); return <HabitCard key={habit.id} habit={habit} category={snapshot.categories.find((item) => item.id === habit.category_id)} streak={snapshot.streaks.find((item) => item.habit_id === habit.id && item.user_id === userId)?.current_streak ?? 0} completed={completed} busy={complete.isPending || undo.isPending} onComplete={() => { setCompleteError(''); complete.mutate(habit.id) }} onUndo={completed ? () => { setCompleteError(''); undo.mutate(habit.id) } : undefined} /> })}</div> : <EmptyState icon={<Flame />} title="Nothing due here" body="Try another category, or enjoy the breathing room." />}</section>{pendingIncoming.length > 0 && <section><div className="mb-2 flex items-center gap-2"><BellRing size={16} className="text-accent" /><h2 className="font-black">One small thing</h2></div><div className="space-y-2">{pendingIncoming.map((item) => <ApprovalAlert key={item.id} redemption={item} snapshot={snapshot} userId={userId} onPreviewDecision={onPreviewDecision} />)}</div></section>}<RhythmStrip snapshot={snapshot} userId={userId} start={weekStart} onPrevious={() => setWeekStart((value) => addDays(value, -7))} onNext={() => setWeekStart((value) => addDays(value, 7))} /></div>
}
